#!/usr/bin/env bash
# Configures a new Ubuntu machine to:
#	Install nginx
#	nginx should be listening to port 80
#	returns a string 'Hello World!' when nginx is queried at its root

sudo apt-get update
sudo apt-get install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
