#!/usr/bin/env bash
# Configures a new Ubuntu machine to:
#	Install nginx
#	nginx should be listening to port 80
#	returns a string 'Hello World!' when nginx is queried at its root

apt-get update
apt-get install nginx
touch var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
service nginx restart
