#!/usr/bin/env bash
# Configures a server with HA Proxy and the following requirements

sudo apt-get update
sudo apt install haproxy -y

# edit config file
server_config=\
"
frontend web-front
        bind *:80
        mode http
        default_backend web-front
backend web-back
        balance roundrobin
        server web-01 54.144.135.222:80 check
        server web-02 54.87.214.225:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
