#!/usr/bin/env bash
# This script is loops 10 times using a while loop displaying "bad luck" for the 
# 4th iteration, "good luck" for the 8th iteration and "Best School" for the other # iterations

i=0
while (( $i < 10 ))
do
        if [ $i -eq 3 ]
        then
                echo "bad luck"
	elif [ $i -eq 7 ]
        then
                echo "good luck"
	else
		echo "Best School"
        fi
        (( i++ ))
done

