#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and displays:
# "4" and then "bad luck from China" for the 4th iteration
# "9" and then "bad luck from Japan" for the 9th iteration
# "17" and then "bad luck from Italy" for the 17th iteration

i=1
while (( i < 21 ))
do
   case $i in
	   4)
	echo -e $i "\nbad luck from China"
	;;
	9)
	echo -e $i "\nbad luck from Japan"
	;;
	17)
	echo -e $i "\nbad luck from Italy"
	;;
	*)
	echo $i
esac
		
        (( i++ ))
done
