#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
#	display hours from 0 to 12
#	display minutes from 1 to 59

hour=1
while (( hour < 13 ))
do
	minute=1
	while (( minute < 60 ))
	do
		echo $minute
		(( minute++ ))
	done
	echo "Hour:" $hour
	(( hour++ ))
done
